apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f g:\f23kube\testapp\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: testapp
  name: testapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: testapp
status:
  loadBalancer: {}
