apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f g:\f23kube\testapp\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: testapp
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: testapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f g:\f23kube\testapp\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: testapp
    spec:
      containers:
      - image: testapp
        imagePullPolicy: ""
        name: testapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
