name: .NET

on:
  push:
    branches: [ "master" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USER }}
        password: ${{  secrets.D_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dfrazzitta/testapp:latest.v1  # Please change the username here
        context: .     
